

# Common params shared by all (or most) sites.
[params]
picture_source_sizes = [ 
  { name = 'xs', width = 500 },
  { name = 'sm', width = 800 },
  { name = 'md', width = 1200 },
  { name = 'lg', width = 1500 }
]

[params.form]
url="https://us-central1-loveyou-forms.cloudfunctions.net/formHandler"
[params.hero_site]
name="Demo"
[params.hero_queries]
[[params.hero_queries.featured_articles]]
key="Type"
operator="in"
match=["blog"]
[params.hero_content]
[params.hero_content.hero]
title="The world’s fastest framework for building websites"
subtitle="""Hugo is **one of the most popular** open-source static site generators. 
With its **amazing speed and flexibility**, Hugo makes building websites fun again.
"""
logo="images/hero/logo.svg"