title = "Love You Forms"
baseURL = "https://loveyouforms.com"
languageCode = "en-us"
themesdir = "../../themes/"
theme = "loveyou"
publishDir = "../../public/LoveYouForms/public"

MetaDataFormat = "yaml"
#SectionPagesMenu = "main"
enableRobotsTXT = true

# Prevent taxonomyt pages from automatically generating by adding as empty string
[taxonomies]
  tag = ""
  group = ""
  category = ""