# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Docs"
  url = "docs"
  weight = 10

[[main]]
  name = "GitHub &nbsp; <i class='fas fa-external-link-alt' style='font-size: 12px;'></i>"
  url = "https://github.com/LoveYouFyi/loveyouforms"
  weight = 20

# Docs sections and links
# Main Sections here, then child pages match to main sections by matching the
# 'identifier' below with the child page's 'parent' [menu.docs.parent] 

[[docs]]
  name = "Overview"
  url = "/docs"
  weight = 1

#[[docs]]
  #name = "Firebase"
  #weight = 10
  #identifier = "firebase"

[[docs]]
  name = "Forms"
  weight = 20
  identifier = "forms"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
